spring.application.name=F1Betting


# Crucial: This allows the console to load inside the Spring frame
server.servlet.context-path=
spring.h2.console.settings.web-allow-others=true


# Force the app to use an in-memory database named 'testdb'
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# This allows the H2 Console to "see" the in-memory DB from your browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Fixes the "Table not found" error we saw earlier
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update